/**
 * Sanity probe — make sure the fixtures generated by
 * `test/fixtures/ocr/generate-fixtures.ts` actually classify the way
 * the OCR e2e tests assume. Cheap to keep around: if someone regenerates
 * a fixture and pdf-lib changes output shape, this fails fast and points
 * to the right rebuild step.
 */

import { promises as fs } from 'fs';
import { join } from 'path';
import { PdfClassifier } from './pdf-classifier';

const FIX = join(__dirname, '../../../../../test/fixtures/ocr');

describe('OCR fixture sanity', () => {
  const classifier = new PdfClassifier();

  it('born-digital-sample.pdf → every page tagged digital', async () => {
    const bytes = await fs.readFile(join(FIX, 'born-digital-sample.pdf'));
    const out = await classifier.classifyBytes(new Uint8Array(bytes));
    expect(out.pageCount).toBeGreaterThan(0);
    expect(out.perPageClassification.every((c) => c === 'digital')).toBe(true);
  });

  it('scanned-sample.pdf → all pages tagged scanned', async () => {
    const bytes = await fs.readFile(join(FIX, 'scanned-sample.pdf'));
    const out = await classifier.classifyBytes(new Uint8Array(bytes));
    expect(out.pageCount).toBeGreaterThan(0);
    expect(out.perPageClassification.every((c) => c === 'scanned')).toBe(true);
  });

  it('hybrid-sample.pdf → mix of digital and scanned pages', async () => {
    const bytes = await fs.readFile(join(FIX, 'hybrid-sample.pdf'));
    const out = await classifier.classifyBytes(new Uint8Array(bytes));
    expect(out.pageCount).toBe(2);
    const tags = new Set(out.perPageClassification);
    expect(tags.has('digital')).toBe(true);
    expect(tags.has('scanned')).toBe(true);
  });
});
