import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Button } from '../../HomePageV2/components/Button';
import { useContractReview } from '@/hooks/useContractReview';
import type { DocumentId } from '@/types/documents';
import styles from './RiskReportTab.module.css';

interface RiskReportTabProps {
  documentId: string | undefined;
}

/**
 * Playbook-Driven Contract Review — starts the review agent on demand and
 * renders the §4 risk report it produces.
 *
 * Asynchronous: "Run review" starts a background run; we then poll for
 * status and swap in the report when it completes. A stored report shows
 * instantly on open without re-running the agent. The runtime badge says
 * which engine produced it (Anthropic Managed Agents vs AWS AgentCore).
 */
export function RiskReportTab({ documentId }: RiskReportTabProps) {
  const { review, start } = useContractReview(
    documentId as DocumentId | undefined,
  );

  const data = review.data;
  const status = data?.status ?? 'not_started';
  const isRunning = status === 'running' || start.isLoading;
  const hasReport = status === 'complete' && Boolean(data?.markdown);

  return (
    <div className={styles.column}>
      <div className={styles.headerBar}>
        <div>
          <strong>Playbook-Driven Risk Report</strong> · generated by the contract
          review agent against Company Legal Playbook v1.0
          {data?.reviewedAt && status === 'complete' && (
            <> · reviewed {new Date(data.reviewedAt).toLocaleString()}</>
          )}
        </div>
        <div className={styles.actions}>
          {hasReport && data?.runtime && (
            <span className={styles.runtimeBadge}>
              {data.runtime === 'agentcore' ? 'AWS AgentCore' : 'Anthropic Agent'}
            </span>
          )}
          <Button
            size="sm"
            onClick={() => start.mutate()}
            disabled={isRunning || !documentId}
          >
            {isRunning ? 'Reviewing…' : hasReport ? 'Re-run review' : 'Run review'}
          </Button>
        </div>
      </div>

      {isRunning && (
        <div className={styles.status}>
          The agent is reviewing the contract clause-by-clause against the
          playbook — reading each clause via the MCP tools, checking the rules,
          and benchmarking against standard positions. This runs in the
          background and can take a few minutes; the report appears here when
          it&apos;s done.
        </div>
      )}

      {status === 'failed' && !start.isLoading && (
        <div className={styles.error}>
          The review couldn&apos;t complete: {data?.error ?? 'unknown error'}. Try
          running it again.
        </div>
      )}

      {status === 'not_started' && !isRunning && (
        <div className={styles.empty}>
          <h3>No risk report yet</h3>
          <p>
            Run the review to have the agent grade this contract against the
            Company Legal Playbook and produce a findings report with rule IDs,
            severities, hard stops, and a prioritised action list.
          </p>
        </div>
      )}

      {hasReport && (
        <article className={styles.report}>
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {data!.markdown!}
          </ReactMarkdown>
        </article>
      )}
    </div>
  );
}
