import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Button } from '../../HomePageV2/components/Button';
import { useContractReview } from '@/hooks/useContractReview';
import type { DocumentId } from '@/types/documents';
import styles from './RiskReportTab.module.css';

interface RiskReportTabProps {
  documentId: string | undefined;
}

/**
 * Playbook-Driven Contract Review — runs the review agent on demand and
 * renders the §4 risk report it produces.
 *
 * The agent reads the already-extracted clauses via the MCP server and
 * grades them against the Company Legal Playbook. Which runtime runs it
 * (Anthropic Managed Agents vs AWS AgentCore) is a server-side .env
 * choice; the response tells us which one, shown as a badge.
 */
export function RiskReportTab({ documentId }: RiskReportTabProps) {
  const review = useContractReview(documentId as DocumentId | undefined);

  return (
    <div className={styles.column}>
      <div className={styles.headerBar}>
        <div>
          <strong>Playbook-Driven Risk Report</strong> · generated by the contract
          review agent against Company Legal Playbook v1.0
        </div>
        <div className={styles.actions}>
          {review.data && (
            <span className={styles.runtimeBadge}>
              {review.data.runtime === 'agentcore' ? 'AWS AgentCore' : 'Anthropic Agent'}
            </span>
          )}
          <Button
            size="sm"
            onClick={() => review.mutate()}
            disabled={review.isLoading || !documentId}
          >
            {review.isLoading
              ? 'Reviewing…'
              : review.data
                ? 'Re-run review'
                : 'Run review'}
          </Button>
        </div>
      </div>

      {review.isLoading && (
        <div className={styles.status}>
          The agent is reviewing the contract clause-by-clause against the
          playbook. This takes a little while — it reads each clause, checks the
          rules, and benchmarks against standard positions.
        </div>
      )}

      {review.isError && (
        <div className={styles.error}>
          The review couldn&apos;t complete:{' '}
          {(review.error as { message?: string } | undefined)?.message ??
            'unknown error'}
          . Try running it again.
        </div>
      )}

      {!review.isLoading && !review.data && !review.isError && (
        <div className={styles.empty}>
          <h3>No risk report yet</h3>
          <p>
            Run the review to have the agent grade this contract against the
            Company Legal Playbook and produce a findings report with rule IDs,
            severities, hard stops, and a prioritised action list.
          </p>
        </div>
      )}

      {review.data && (
        <article className={styles.report}>
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {review.data.markdown}
          </ReactMarkdown>
        </article>
      )}
    </div>
  );
}
